---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 2944184508-yUCCWiKnMtAT1kysOdfLMkSmnia72PDA24gcHeo
:access_token_secret: 4ycWrHQRLDvdasOHsRmmW3JM4XFygbmfPBPofqBn20hyo
